package com.glumes.ffmpeglib

const val FFMPEG_GET_META_DATA_INFO = 0x00
const val FFMPEG_GET_FFMPEG_INFO = 0x01

const val FFMPEG_CODEC_DECODE_VIDEO = 0x02
const val FFMPEG_CODEC_ENCODE_VIDEO = 0x03

const val FFMPEG_CODEC_DECODE_AUDIO = 0x04
const val FFMPEG_CODEC_ENCODE_AUDIO = 0x05

const val FFMPEG_MUXER_DEMUXER_SIMPLE = 0x06
const val FFMPEG_MUXER_DEMUXER_STANDARD = 0x07