package com.glumes.ffmpeglib

const val FFMPEG_GET_META_DATA_INFO = 0x00
const val FFMPEG_GET_FFMPEG_INFO = 0x01

const val FFMPEG_CODEC_MP4_TO_YUV = 0x10
const val FFMPEG_CODEC_MP4_TO_H264 = 0x11

const val FFMPEG_CODEC_YUV_TO_H264 = 0x12
const val FFMPEG_CODEC_H264_TO_YUV = 0x13

const val FFMPEG_CODEC_H264_TO_MP4 = 0x14
const val FFMPEG_CODEC_YUV_TO_MP4 = 0x15


const val FFMPEG_CODEC_DECODE_AUDIO = 0x20
const val FFMPEG_CODEC_ENCODE_AUDIO = 0x21

const val FFMPEG_MUXER_DEMUXER_SIMPLE = 0x30
const val FFMPEG_MUXER_DEMUXER_STANDARD = 0x31
